server:
  - changed-files:
      - any-glob-to-any-file:
          - "api-contracts/**"
          - "server/**"
          - "gradle/**"
          - "build.gradle.kts"
          - "settings.gradle.kts"
          - "gradle.properties"
          - ".github/workflows/server_pr.yml"
          - ".github/workflows/server_pr.yml"
          - "Dockerfile"
          - "infra/docker-compose.yml"

mobile:
  - changed-files:
        - any-glob-to-any-file:
            - "api-contracts/**"
            - "build-logic/**"
            - "library/**"
            - "composeApp/**"
            - "iosApp/**"
            - "desktop/**"
            - "gradle/**"
            - "*.gradle.kts"
            - ".maestro/**"